version: '3'
services:
  parser:
    restart: always
    build: .
    image: app
    links:
      - db
    depends_on:
      - db
    environment:
      - 'CELERY_BACKEND_URL=redis://redis'
      - 'CELERY_BROKER_URL=redis://redis'
      - 'MONGO_HOST=db'
      - NODE
      - BLOCK_FROM_UPDATE_COMMENT_BY_VOTE
    tty: true
  db:
    image: "mongo"
    ports:
      - "0.0.0.0:27018:27017"
    volumes:
      - ./data:/data/db
  parser-worker:
    command: python main.py
    image: app
    environment:
      - 'CELERY_BACKEND_URL=redis://redis'
      - 'CELERY_BROKER_URL=redis://redis'
      - 'MONGO_HOST=db'
    links:
      - db
      - redis
    restart: always
    tty: true
  celery-worker:
    command: celery -A tasks worker
    image: app
    environment:
      - 'CELERY_BACKEND_URL=redis://redis'
      - 'CELERY_BROKER_URL=redis://redis'
      - 'MONGO_HOST=db'
    links:
      - db
      - redis
    restart: always
    tty: true
  redis:
    command: redis-server
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    restart: always
    tty: true
