version: '3'
services:
  parser:
    restart: always
    build: .
    links:
      - db
    depends_on:
      - db
    environment:
      - MONGO_HOST=mongo
      - NODE
  db:
    image: "mongo"
    ports:
      - "0.0.0.0:27018:27017"
    volumes:
      - ./data:/data/db
